# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

# pytest:
#   stage: test
#   before_script:
#     - pip install pytest pytest-cov
#   script:
#     - pytest --cov=meteor --cov-report xml
#     - coverage report
#   coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
#   artifacts:
#     reports:
#       coverage_report:
#         coverage_format: cobertura
#         path: coverage.xml
#   only:
#     - dev

pylint:
  stage: test
  before_script:
    - pip install pylint-gitlab
  script:
    - pylint --output-format=text $(find -type f -name "*.py" ! -path "**/.venv/**") | tee pylint.txt
    - score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
    - echo "Pylint score was $score"
    - anybadge --value=$score --file=public/pylint.svg pylint
  artifacts:
    paths:
      - public/pylint.svg
  only:
    - dev

run:
  stage: build
  before_script:
    - pip install twine
  script:
    - python setup.py bdist_wheel
    - TWINE_PASSWORD=${CI_JOB_TOKEN} TWINE_USERNAME=gitlab-ci-token python -m twine upload --skip-existing --repository-url ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi dist/*
  artifacts:
    paths:
      - dist/*.whl
  only:
    - dev

build_conda:
  image: continuumio/miniconda3:latest
  stage: build
  variables:
    CI_DEBUG_TRACE: "false"
  before_script:
    - conda config --add channels conda-forge
    - conda config --add channels bioconda
    - conda config --set anaconda_upload yes
    - conda update  -n base -c defaults conda
    - conda install -y conda-verify
    - conda install -y anaconda-client
    - conda install -y conda-build
    - conda install -y git
    - anaconda login --hostname "$DOCKER_HOST" --username "$DOCKER_USER" --password "$DOCKER_PASS"
  script:
    - conda build conda_recipe
  after_script:
    - anaconda logout
  only:
    - dev


pages:
  stage: deploy
  before_script:
     - pip install sphinx sphinx-rtd-theme myst_parser
  script:
    - cd doc
    - make html
    - mv build/html/ ../public/
  artifacts:
    paths:
      - public
  only:
    - dev