{% set name = "meteor" %}
#{% set version = "2.0.0" %}

package:
    name: {{ name }}
    version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

channels:
    - conda-forge
    - bioconda
    - defaults

source:
      path: ..

build:
    noarch: python
    number: 1
    script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --no-cache-dir -vvv
    entry_points:
        - meteor = meteor.meteor:main
    run_exports:
        - {{ pin_subpackage('meteor', max_pin="x") }}

requirements:
    host:
        - python >=3.10
        - pip
        - poetry-core
    run:
        - python >=3.10
        - bowtie2 >=2.3.5
        - pysam
        - pyarrow
        - pandas
        - ete3
        - packaging
        - cogent3
        - biom-format
        - bgzip
        - freebayes >=1.2
test:
    commands:
        - meteor -h
        - bowtie2 -h
        - freebayes -h
    imports:
        - pysam
        - pandas
        - pyarrow
        - ete3
        - packaging
        - biom
        - cogent3
        - bgzip

about:
  home: https://github.com/metagenopolis/meteor
  license: GPL (>= 3)
  license_file: COPYING
  summary: 'Meteor is a plateform for quantitative metagenomics profiling of complex ecosystems.'
  description: |
    Meteor relies on genes catalogue to perform specie level taxonomic assignments and functional analysis.
  license_family: GPL3
