{% set name = "meteor" %}
#{% set version = "2.0.0" %}

package:
    name: {{ name }}
    version: "{{ environ['GIT_DESCRIBE_TAG'] }}"

channels:
    - conda-forge
    - bioconda
    - defaults

source:
      path: ..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
    host:
        - python >=3.10
        - poetry
    run:
        - python >=3.10
        - bowtie2 >=2.3.5
        - pysam
        - pyarrow
        - pandas
        - ete3
        - packaging
        - cogent3
        - biom-format
        - freebayes >=1.2
test:
    commands:
        - meteor -h
        - bowtie2 -h
        - freebayes -h
    imports:
        - pysam
        - pandas
        - pyarrow
        - ete3
        - packaging
        - biom
        - cogent3

about:
  home: https://github.com/metagenopolis/meteor
  license: GPL (>= 3)
  license_file: COPYING
  summary: 'Meteor is a plateform for quantitative metagenomics profiling of complex ecosystems.'
  description: |
    Meteor relies on genes catalogue to perform specie level taxonomic assignments and functional analysis.
  license_family: GPL3
