package:
    name: meteor
    version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
    - git_url: https://forgemia.inra.fr/metagenopolis/meteor.git
      git_ref: environ.get('GIT_DESCRIBE_TAG', '')
      git_tag: origin/dev

build:
  noarch: python
  script: {{ PYTHON }} setup.py install
  # script: {{ PYTHON }} -m pip install .

requirements:
    build:
        - {{ compiler('cxx') }}
        - make
    host:
        - python>=3
    run:
        - python
        - gxx
        - bowtie2
test:
    commands:
        - meteor -h
        - meteor-counter -h
        - meteor-profiler -h

about:
  home: https://mgps.eu/
  license: GPL (>= 3)
  summary: 'Meteor is a plateform for quantitative metagenomics profiling of complex ecosystems.'
  description: |
    Meteor relies on genes catalogue to perform specie level taxonomic assignments and functional analysis. 
  dev_url: https://forgemia.inra.fr/metagenopolis/meteor
  license_family: GPL3
