name: conda recipe

# Controls when the workflow will run
on:
  # Triggers the workflow on schedule but only for the default branch (which is master)
  schedule:
   - cron: '0 7 * * 1-5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "check_recipe"
  check_recipe:
    name: test conda recipes on ${{ matrix.os }} with ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest','macos-latest']
        python-version: ["3.7", "3.11"]
    steps:
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,bioconda,aghozlane,defaults
      - name: Set up test environment
        shell: bash -l {0}
        run: |
            conda install -y meteor
      - name: check installation
        shell: bash -l {0}
        run: |
            python --version
            meteor --version
      - name: all workflow run
        shell: bash -l {0}
        run: |
            meteor test